name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # GitHub kodlarını indir
      - name: Kodu indir
        uses: actions/checkout@v4

      # Python
      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Java 17
      - name: Java JDK 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Python bağımlılıklarını kur
      - name: Bağımlılıkları kur
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # APK oluştur
      - name: APK oluştur
        run: |
          yes | flet build apk \
            --verbose \
            --permissions location

      # APK'yı Actions'a yükle
      - name: APK artifact yükle
        uses: actions/upload-artifact@v4
        with:
          name: metevra-weather-apk
          path: build/apk/*.apk
          if-no-files-found: error
